#!/bin/bash
mkdir /usr/local/etc
mkdir /usr/local/etc/EmrMonitoringTool
mkdir /usr/local/etc/EmrMonitoringTool/shell-backend
mkdir /usr/local/etc/EmrMonitoringTool/shell-backend/lib

if [ ! -f /usr/local/etc/EmrMonitoringTool/dhis-emt-datasetValueSets.json ]; then
	touch /usr/local/etc/EmrMonitoringTool/dhis-emt-datasetValueSets.json
fi
